// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/agency-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var AGENCY = {
  name: "ERA DUPONT ROMAIN IMMOBILIER",
  brand: "ERA Dupont Romain",
  phone: "04 68 66 57 18",
  phoneE164: "+33468665718",
  website: "https://era-dupontromain.immo",
  city: "Perpignan",
  region: "Pyr\xE9n\xE9es-Orientales (66)",
  country: "France",
  services: [
    "Estimation locative offerte",
    "Gestion locative",
    "Mise en location",
    "Accompagnement propri\xE9taires (DPE F/G, loyers impay\xE9s, vacance locative)"
  ],
  googleReviews: { rating: 4.6, count: 136 }
};
var agency_info_default = defineTool({
  name: "get_agency_info",
  title: "Informations sur l'agence ERA Dupont Romain",
  description: "Retourne les coordonn\xE9es et services de l'agence ERA Dupont Romain (Perpignan et Pyr\xE9n\xE9es-Orientales) : t\xE9l\xE9phone, site web, zone d'intervention, note Google et prestations propos\xE9es.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `${AGENCY.name}
T\xE9l\xE9phone : ${AGENCY.phone}
Site : ${AGENCY.website}
Zone : ${AGENCY.city}, ${AGENCY.region}, ${AGENCY.country}
Avis Google : ${AGENCY.googleReviews.rating}/5 (${AGENCY.googleReviews.count} avis)
Services : ${AGENCY.services.join(", ")}`
      }
    ],
    structuredContent: AGENCY
  })
});

// src/lib/mcp/tools/submit-estimation.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
var N8N_WEBHOOK_URL = "https://n8n.srv864634.hstgr.cloud/webhook/c15fe03b-332b-405e-b285-3c660fb06c0e";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get(name);
}
var submit_estimation_default = defineTool2({
  name: "submit_estimation",
  title: "Soumettre une demande d'estimation locative",
  description: "Envoie une demande d'estimation de loyer \xE0 ERA Dupont Romain (Perpignan et 66). Coordonn\xE9es obligatoires (nom, pr\xE9nom, email, t\xE9l\xE9phone) et informations sur le bien optionnelles. La r\xE9ponse est envoy\xE9e par l'agence sous 24 h.",
  inputSchema: {
    consentement_rgpd: z.boolean().describe(
      "Confirmation que la personne a explicitement consenti \xE0 \xEAtre recontact\xE9e par ERA Dupont Romain et a \xE9t\xE9 inform\xE9e de la politique de confidentialit\xE9 : https://era-dupontromain.immo/confidentialite"
    ),
    nom: z.string().min(1).describe("Nom de famille du propri\xE9taire."),
    prenom: z.string().min(1).describe("Pr\xE9nom du propri\xE9taire."),
    email: z.string().email().describe("Adresse email de contact."),
    telephone: z.string().min(6).describe("Num\xE9ro de t\xE9l\xE9phone fran\xE7ais."),
    ville: z.string().optional().describe("Ville du bien (ex. Perpignan)."),
    codePostal: z.string().optional().describe("Code postal du bien."),
    adresse: z.string().optional().describe("Adresse ou rue du bien."),
    type: z.enum(["appartement", "maison", "immeuble", "autre"]).optional().describe("Type de bien."),
    surface: z.string().optional().describe("Surface en m\xB2."),
    pieces: z.string().optional().describe("Nombre de pi\xE8ces."),
    chambres: z.string().optional().describe("Nombre de chambres."),
    dpe: z.enum(["A", "B", "C", "D", "E", "F", "G", "non-connu"]).optional().describe("Classe DPE du bien."),
    meuble: z.enum(["oui", "non"]).optional().describe("Bien meubl\xE9 ou non."),
    gestion: z.enum(["oui", "non", "peut-etre"]).optional().describe("Int\xE9r\xEAt pour une gestion locative par l'agence.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: true
  },
  handler: async (input) => {
    const { consentement_rgpd, ...fields } = input;
    if (consentement_rgpd !== true) {
      return {
        content: [
          {
            type: "text",
            text: "Consentement RGPD manquant : la demande n'a pas \xE9t\xE9 transmise. La personne doit explicitement accepter d'\xEAtre recontact\xE9e par ERA Dupont Romain et \xEAtre inform\xE9e de la politique de confidentialit\xE9 (https://era-dupontromain.immo/confidentialite)."
          }
        ],
        isError: true
      };
    }
    const payload = {
      ...fields,
      rgpd: "true",
      source: "mcp",
      source_form: "mcp-server",
      timestamp: (/* @__PURE__ */ new Date()).toISOString()
    };
    const secret = runtimeEnv("N8N_WEBHOOK_SECRET") ?? "";
    const res = await fetch(N8N_WEBHOOK_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-webhook-secret": secret
      },
      body: JSON.stringify(payload)
    });
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      return {
        content: [
          {
            type: "text",
            text: `La demande n'a pas pu \xEAtre transmise (HTTP ${res.status}). ${body}`
          }
        ],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Demande d'estimation transmise \xE0 ERA Dupont Romain. L'agence recontactera ${input.prenom} ${input.nom} sous 24 h au ${input.telephone} ou par email (${input.email}).`
        }
      ],
      structuredContent: { ok: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "era-dupont-romain-mcp",
  title: "ERA Dupont Romain \u2014 Estimation locative",
  version: "0.1.0",
  instructions: "Outils publics de l'agence ERA Dupont Romain (Perpignan, Pyr\xE9n\xE9es-Orientales). Utilise `get_agency_info` pour obtenir les coordonn\xE9es et prestations, et `submit_estimation` pour transmettre une demande d'estimation locative \xE0 l'agence (r\xE9ponse sous 24 h).",
  tools: [agency_info_default, submit_estimation_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
